spring:
  application:
    name: stock-trading-simulator
    
  datasource:
    url: jdbc:postgresql://localhost:5432/stocktrade
    username: stocktrade_user
    password: stocktrade_pass
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  security:
    user:
      name: admin
      password: admin123
      
server:
  port: 8080
  
# Stock API Configuration
stock:
  api:
    alpha-vantage:
      api-key: ${ALPHA_VANTAGE_API_KEY:demo}
      base-url: https://www.alphavantage.co/query
    finnhub:
      api-key: ${FINNHUB_API_KEY:demo}
      base-url: https://finnhub.io/api/v1
      
# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours in milliseconds
  
# Logging
logging:
  level:
    com.stocktrade: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
